# -*- coding: utf-8 -*-
"""streamlit_pekpppcsv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZrQWNXU4cTdO4lyvLi1_SXALfkO2IvN
"""

import streamlit as st
import pandas as pd

st.set_page_config(page_title="CSV Transformer", layout="centered")

st.title("📄 CSV Transformer Tool")
st.write("Upload your CSV file and convert it automatically.")

# Upload file
file = st.file_uploader("📤 Upload CSV file", type=["csv"])

def transform_users(df, id_col, name_col):
    output = []

    # Ambil ID parent dari baris pertama (index 0)
    parent_id = df.iloc[0][id_col]

    # Iterasi dimulai dari baris ke-2 (index 1) untuk melewatkan data parent
    for _, row in df.iloc[1:].iterrows():
        # Memastikan mengambil nilai berdasarkan nama kolom yang dipilih user
        user_id = row[id_col]
        user_name = row[name_col]  # Menggunakan nama kolom nama yang sesuai

        # form_sheet_id berulang dari 1 sampai 3
        for c in [1, 2, 3]:
            new_row = {
                "name": user_name,          # Mengisi kolom 'name' dengan nama teks instansi (bukan ID)
                "template_id": 1,
                "form_sheet_id": c,
                "is_public": 1 if c == 3 else 0,
                "isi": "",
                "lihat": ""
            }

            # Aturan kolom 'isi'
            if c == 1:
                new_row["isi"] = user_id
            elif c == 2:
                new_row["isi"] = parent_id
            elif c == 3:
                new_row["isi"] = "" 

            # Aturan kolom 'lihat'
            if c == 3:
                new_row["lihat"] = user_id

            output.append(new_row)

    return pd.DataFrame(output)

if file:
    try:
        # Read CSV safely
        df = pd.read_csv(file, sep=None, engine='python')
        
        # Bersihkan spasi pada nama kolom asal agar tidak error saat pencocokan
        df.columns = df.columns.str.strip()

        st.success("✅ File uploaded successfully!")

        # Preview data asal
        st.subheader("🔍 Data Preview")
        st.dataframe(df.head())

        # Column selection (user-friendly)
        st.subheader("⚙️ Select Columns")
        columns = df.columns.tolist()

        # Deteksi otomatis kolom agar user tidak salah pilih
        default_id_index = next((i for i, col in enumerate(columns) if 'id' in col.lower()), 0)
        default_name_index = next((i for i, col in enumerate(columns) if 'nam' in col.lower()), 0)

        id_col = st.selectbox("Select ID column (e.g., 'Id')", columns, index=default_id_index)
        name_col = st.selectbox("Select Name column (e.g., 'Name')", columns, index=default_name_index)

        # Process button
        if st.button("🚀 Transform Data"):
            result = transform_users(df, id_col, name_col)

            st.success("🎉 Transformation complete!")

            # Preview hasil akhir
            st.subheader("📊 Output Preview")
            st.dataframe(result.head(15)) 

            # Download
            st.download_button(
                "⬇️ Download CSV",
                result.to_csv(index=False),
                "output.csv",
                mime="text/csv"
            )

    except Exception as e:
        st.error("❌ Error processing file")
        st.write(str(e))

else:
    st.info("Please upload a CSV file to begin.")
