# -*- coding: utf-8 -*-
"""streamlit_pekpppcsv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZrQWNXU4cTdO4lyvLi1_SXALfkO2IvN
"""

import streamlit as st
import pandas as pd

st.set_page_config(page_title="CSV Transformer", layout="centered")

st.title("📄 CSV Transformer Tool")
st.write("Upload your CSV file and convert it automatically.")

# Upload file
file = st.file_uploader("📤 Upload CSV file", type=["csv"])

def transform_users(df, id_col, name_col):
    output = []

    # Baris pertama (index 0) adalah parent (ID 529 dalam contoh)
    parent_id = df.iloc[0][id_col]

    # Iterasi dimulai dari baris ke-2 di dataframe (index 1 dst) karena aturan menyatakan baris 1 & 2 di csv adalah deskripsi/parent
    for _, row in df.iloc[1:].iterrows():
        user_id = row[id_col]
        name = row[name_col]

        # form_sheet_id berulang dari 1 sampai 3
        for c in [1, 2, 3]:
            new_row = {
                "name": name,
                "template_id": 1,
                "form_sheet_id": c,
                "is_public": 1 if c == 3 else 0,
                "isi": "",
                "lihat": ""
            }

            # Aturan kolom 'isi'
            if c == 1:
                new_row["isi"] = user_id
            elif c == 2:
                new_row["isi"] = parent_id
            elif c == 3:
                new_row["isi"] = "" # Kosong saat form_sheet_id = 3 (atau sesuai aturan ke-5 Anda: 'tidak diisi ketika form_sheet_id=1' tampaknya maksudnya adalah ketika c=3 jika merujuk gambar)

            # Aturan kolom 'lihat'
            if c == 3:
                new_row["lihat"] = user_id

            output.append(new_row)

    return pd.DataFrame(output)

if file:
    try:
        # Read CSV safely
        df = pd.read_csv(file, sep=None, engine='python')
        df.columns = df.columns.str.strip().str.lower()

        st.success("✅ File uploaded successfully!")

        # Preview data
        st.subheader("🔍 Data Preview")
        st.dataframe(df.head())

        # Column selection (user-friendly)
        st.subheader("⚙️ Select Columns")

        columns = df.columns.tolist()

        id_col = st.selectbox("Select ID column", columns)
        name_col = st.selectbox("Select Name column", columns)

        # Process button
        if st.button("🚀 Transform Data"):
            result = transform_users(df, id_col, name_col)

            st.success("🎉 Transformation complete!")

            # Preview result
            st.subheader("📊 Output Preview")
            st.dataframe(result.head(15)) # Menampilkan 15 baris pertama untuk melihat siklus perulangan id 1-3

            # Download
            st.download_button(
                "⬇️ Download CSV",
                result.to_csv(index=False),
                "output.csv",
                mime="text/csv"
            )

    except Exception as e:
        st.error("❌ Error processing file")
        st.write(str(e))

else:
    st.info("Please upload a CSV file to begin.")
