# -*- coding: utf-8 -*-
"""streamlit_pekpppcsv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZrQWNXU4cTdO4lyvLi1_SXALfkO2IvN
"""

import streamlit as st
import pandas as pd

st.title("CSV Transformer")

file = st.file_uploader("Upload CSV")

def transform_users(df):
    output = []
    default_id = df.iloc[0]['id']

    for _, row in df.iterrows():
        user_id = row['id']
        name = row['name']

        for c in [1,2,3]:
            new_row = {
                "name": name,
                "template_form_she": 1,
                "is_public": c,
                "is_flag": 1 if c == 3 else 0,
                "isi": "",
                "lihat": ""
            }

            if c == 1:
                new_row["isi"] = user_id
            elif c == 2:
                new_row["isi"] = default_id

            if c == 3:
                new_row["lihat"] = user_id

            output.append(new_row)

    return pd.DataFrame(output)

if file:
    df = pd.read_csv(file)
    result = transform_users(df)

    st.download_button(
        "Download CSV",
        result.to_csv(index=False),
        "output.csv"
    )

# requirements.txt
reqs = ["streamlit", "pandas"]
with open("requirements.txt", "w") as f:
    f.write("\n".join(reqs))

